### ISSUE TITLE
add value to set `envFrom` in Pods

### ISSUE THREAD

**Issue by c-thiel** [airflow-helm/charts#117]
**What is your feature request?**
Currently there is no way to specify envFrom from the values.yaml - only env can be defined.
We should add an option to specify `extraEnvFrom` similar to `extraEnv ` in the values.yaml.

As far as I can see this could be added to the `pods.tpl`: https://github.com/airflow-helm/charts/blob/8611c766992a9f7156aad450f17beb2213cf667c/charts/airflow/templates/_helpers/pods.tpl#L263

**Comment by thesuperzapper** [comment]
@c-thiel and @mthoretton can we discuss the reason you need this feature, I am a bit hesitant to let users set this (as users will not realize that Containers only pick up new environment variables if they are restarted).

**Comment by v-yarotsky** [comment]
I also have a use-case for this. I'd like to create a helm chart that uses the chart from this repo as a dependency. My chart would create a ConfigMap and a Secret (via kubernetes-external-secrets as one option) that would contain all the necessary environment variables, and then I'd set `extraEnvFrom` in the chart's `values.yaml` to source environment variables for pods from those kubernetes objects.
Ideally, my chart's `values.yaml` would look like this:
```yaml
airflow:
  ...
  extraEnvFrom:
  - configMapRef: airflow-extra-config
  - secretRef: airflow-extra-secrets
  ...
```
Creating the ConfigMap in the "parent" chart would allow me to set reasonable values for some tweakables of airflow, while allowing the end user to customize others.

**Comment by thesuperzapper** [comment]
@v-yarotsky did you know that pods [don't receive environment variable updates](https://kubernetes.io/docs/concepts/configuration/secret/#environment-variables-are-not-updated-after-a-secret-update) from Secrets/Configmaps until they are restarted? This is the primary reason I am against an `airflow.extraEnvFrom` value, as users would end up with inconsistent configs across all their pods. (NOTE: we solve this in the chart by [annotating the Pod templates](https://github.com/airflow-helm/charts/blob/bbd4a944bc88e7e739a9c9676f2dbfca2939d178/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L49) with the hash of our secret)

I would love to understand why you need to use this chart as a dependency (and if we can improve the chart to make that not needed), but you should be able to set default configs with `airflow.configs` (as long as the downstream user doesn't explicitly set it to `{}`).

**Comment by mthoretton** [comment]
@thesuperzapper thanks for following up and sorry for the delay.

When I opened the PR I was still figuring out a good way to work with secrets (and Hashicorp Vault). And in this context, your arguments about env vars not being refreshed is totally right. For this exact reason I now use Vault pod annotations and an extra custom sidecar container that will kill the vault container when the airflow dag container dies... Otherwise the vault sidecar will hang forever as it waits for the pod to be killed from outside. I will probably create a PR or open an issue to talk about it, maybe it could be interesting for somebody.

Back to your questions.
After some time, it turns out the only remaining reason I still use this chart as a sub airflow chart is because I create secrets that I reference later. For instance SMTP_PASSWORD, FERNET_KEY and KEYCLOAK_SECRET (used for RBAC-OIDC). As they're not that sensisitive I guess I could make my life easier, remove the "umbrella chart" and straight set those 3 variables in clear in the config. Or use the "extramanifest" or some recent addition to this chart I may have missed.

So in my case I don't have anymore, at this time, a good reason to get this feature. Also I agree with you about values not being updated until restart will bring confusion and headaches.

I work with this chart for quite a while now (always via a fork as I had many specific needs) but now absolutely everything I need is covered (but a small thing I'll PR about). Also I really like the technical decisions and improvements (like around git-sync or users/vars sync). Great work, thanks a lot!

**Comment by thesuperzapper** [comment]
BTW @mthoretton when I deploy the chart for companies I almost always use a "wrapper" chart which uses this one as a dependency so I can create the required Secrets and other resources I need.

So I don't necessarily recommend stopping doing that.
