### ISSUE TITLE
Jobs (db upgrade, etc.) should have node selector/affinity values

### ISSUE THREAD

**Issue by mejran** [airflow-helm/charts#130]
**What is your feature request?**

It'd be useful for jobs to have node selector and affinity values so that you can control which nodes jobs run on. In our case certain nodes are in a security group that does not have access to the airflow DB so we get jobs that get stuck on helm deployment.

**What alternatives have you considered?**

Changing the security group configuration of our cluster but we'd like to avoid that long term.

**Comment by demetrioi** [comment]
Hi.

I have the same problem. In my case I have a cluster with Windows and Linux nodes. I cannot select on which server my job will be deployed. Then the job fail when is deployed to a Windows node.

**Comment by demetrioi** [comment]
I managed to find a workaround.

You can put the nodeselector at the namespace level. Then all pods created on that namespace will be assigned to a specific node.

kubectl edit namespace yourNamespace

https://stackoverflow.com/questions/52487333/how-to-assign-a-namespace-to-certain-nodes

**Comment by thesuperzapper** [comment]
Closing this because PR https://github.com/airflow-helm/charts/pull/281 added the ability to set node selector/affinity for user/connections/pools/variables jobs.

The only job left is the `airflow db upgrade`, which will be replaced after https://github.com/airflow-helm/charts/issues/317 is resolved.
