### ISSUE TITLE
Jobs (db upgrade, etc.) should allow custom pod annotations

### ISSUE THREAD

**Issue by thetko85** [airflow-helm/charts#156]
**What is your feature request?**

It would be good to allow custom annotations to be assigned to job pods. A use case for this is if we want to add in the annotation 
sidecar.istio.io/inject: "false" just for job pods, so that istio sidecar is not injected. 

Note: the generic podAnnotations won't work as we still want the istio sidecar injected to the web deployment.

**What alternatives have you considered?**

- Do not auto enable auto-injection in the cluster. However this would break some of our other processes.

**Comment by thesuperzapper** [comment]
Cool, sounds good will do this in the next minor release.

**Comment by thetko85** [comment]
Great to hear, thanks!!!

**Comment by thesuperzapper** [comment]
This isn't done yet, reopening.

**Comment by thesuperzapper** [comment]
Closing this because PR https://github.com/airflow-helm/charts/pull/281 added the ability to set custom pod annotations for user/connections/pools/variables jobs.

The only job left is the `airflow db upgrade`, which will be replaced after https://github.com/airflow-helm/charts/issues/317 is resolved.
