### ISSUE TITLE
existence of airflow 2.0.2 breaks some pip installs 

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#169]
Currently if you install `apache-airflow-providers-databricks==1.0.1` with `airflow.extraPipPackages`, it will install `airflow-apache==2.0.2`, which breaks the scheduler pod.

There are a few ways we could prevent pip installing the newer version of airflow, including using constraints, and just specifying `apache-airflow==2.0.1` at the end of the pip install list.

Issues with these ideas:
* the default constraints file doesn't include `apache-airflow==2.X.X`, so cant help us: 
https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt
* adding `apache-airflow` to the pip install list will probably install other package the user does not want

I guess we could build our own constraints file by appending the output of `airflow version` to a text file, and referencing it in the `pip install --constraint ./the_file.txt ...`

PS: I am still not clear where the requirements.txt (or similar) for `apache-airflow-providers-databricks` is defined

**Comment by griseau** [comment]
Agree with you that adding apache-airflow==2.0.1 is not the ideal case. 

Airflow provides many constraint files with this url : https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt 

So maybe best option could  be to add values like `airflow.version` and `airflow.python.version` instead of setting the image ? And then reuse them for the constraint file ?

**Comment by griseau** [comment]
@thesuperzapper, don't know why I didn't think about it before, but here is a "hacky" solution to use constraint file. 
Add "-c" and constraint file path as a extraPipPackages. 

I tried with the following and it worked
```yaml
airflow.extraPipPackages:
    - "-c"
    - "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt"
    - "apache-airflow-providers-databricks==1.0.1"
```

**Comment by thesuperzapper** [comment]
@griseau but when I tested including a constant file, the scheduler still failed.

**Comment by griseau** [comment]
It's weird because I just tested it with airflow 2.0.1, and it worked perfectly. Which version did you use ?

**Comment by griseau** [comment]
Constraint file doesn't include constraint on apache-airflow version, so I guess it's the reason

**Comment by potiuk** [comment]
constraints should only be used when you are installing as "fresh" installation. When you are adding extra dependency (especially released after airflow) , there is no reason to use constraints for that. 

Generally just installing extra `apache-airflow-providers-databricks==1.0.1` should not generally automatically upgrade Airflow to 2.0.2 unless you specifically request it (via `--upgrade` `--upgrade-strategy eager`) 

I do not know how the works, but if it rebuilds the image using the Dockerfile, then by default, the Dockerfile uses latest released version of airflow, if you want to pin it to specific version, you should specify it as AIRFLOW_VERSION.  So maybe the problem is that the image is now installed with two different versions of Airflow because only one is rebuild with latest airflow? I am speculating now though.

> PS: I am still not clear where the requirements.txt (or similar) for `apache-airflow-providers-databricks` is defined
They are defined in the package itself: https://pypi.org/project/apache-airflow-providers-databricks/
```
requests >=2.20.0, <3
```

**Comment by potiuk** [comment]
Just one more comment here. In case you use the automated custom image building in chart (whch I believe might be the case) with 2.0.2 we've updated documentation about building the image. so you can take a look and see all the documentation here including the reference parameters: 

https://airflow.apache.org/docs/docker-stack/build.html#customizing-the-image

**Comment by thesuperzapper** [comment]
I now understand why this is happening, it's nothing to do with constraints, it's simply that our pip-install init-container was never seeing the pre-installed packages in the `apache/airflow` container image.

That is, `pip install --target /opt/python/site-packages apache-airflow-providers-databricks==1.0.1` was installing all its dependancies (including `apache-airflow==2.0.2`) into `/opt/python/site-packages`, because pip ignores the user `/home/airflow/.local/lib/python3.8/site-package` folder for dependency resolution when `--target` is specified.

I am still thinking about the best aproach to fix this, but here is one option:
* Copy everything from `/home/airflow/.local/lib/python3.8/site-package` to `/opt/python/site-packages` before running `pip install --target /opt/python/site-packages ...`

**Comment by potiuk** [comment]
OK. I looked it up and I see where it is coming from. 

I think the best would be the other way round. You should install with `--user flag`,  then copy the whole `/home/airflow/.local` directory and mount it as `/home/airflow/.local` 

This is exactly what happens when the image is built. We first install it in `build` segment and then copy over the `.local` directory   to the final image.

**Comment by manojbalaji1** [comment]
@thesuperzapper any updates on this issue?

**Comment by thesuperzapper** [comment]
Hi all, this should be resolved after version `8.0.9` of the chart.

I would love it if @manojbalaji1 or @griseau could confirm.

**Comment by manojbalaji1** [comment]
@thesuperzapper thanks for the update, it works for me for using aws airflow dependency!

**Comment by griseau** [comment]
Thanks @thesuperzapper ! It worked on my side also
