### ISSUE TITLE
An example of running upgrade-db job

### ISSUE THREAD

**Issue by ilgarm** [airflow-helm/charts#191]
Hello! Could you pls provide an example how to use `job-upgrade-db.yaml` job template? Thank you!

**Comment by thesuperzapper** [comment]
@ilgarm ?? 

You dont need to "use" it, just install the chart.

**Comment by ilgarm** [comment]
@thesuperzapper thanks for your kind reply. Will it just work with helm --wait option? Actually, I am not using helm directly, but ArgoCD which also does not use helm to install the application, afaik, it only renders the final yaml through helm. I probably have to investigate more, but upgrade-db job was not even provisioned when installing through ArgoCD.

**Comment by thesuperzapper** [comment]
@ilgarm If you are specifying `helm --wait` you must set the `helmWait` value to `true`:
https://github.com/airflow-helm/charts/blob/airflow-8.0.9/charts/airflow/values.yaml#L1-L3

Otherwise the upgrade-db job will never be deployed, see https://github.com/helm/helm/issues/5891#issuecomment-829738750 for reference.

**Comment by ilgarm** [comment]
@thesuperzapper thank you! I somehow missed the default value there. Will check that.
