### ISSUE TITLE
Use `constraints.txt`  with `extraPipPackages`

### ISSUE THREAD

**Issue by whatnick** [airflow-helm/charts#221]
**What is your feature request?**

Include constraints file by default when installing extra pip packages.

**What alternatives have you considered?**

Creating custom docker images or pod operators for complex python environments.

**Comment by thesuperzapper** [comment]
@whatnick there was some discussion about this, and people @Potiuk suggested that the constraints are only intended for when you install airflow (and its providers)

Since `extraPipPackages` is used by people for a mixture of both airflow providers, __and__ other python packages, I am not sure that including the constraints by default is a good idea. A user might specify a different version of a package in `extraPipPackages` than is specified in the constraints file, their request would be ignored as the version in the constraints file would be installed.

Docs for airflow constraints files: 
https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files

**Comment by potiuk** [comment]
Correct. You can simply get the specific versions of your dependencies. You can even install newer versions of those packages which are in constraints if new versions of those have been released. Constraints are really snapshot at the moment of release. 

BTW. Let me also remind the installing the dependencies on the flight when you start container is a very bad idea - also discussed in the same thread. What you REALLY should do is to build your own image and use it instead of the Airflow reference image. It's really easy  and documented in airflow : https://airflow.apache.org/docs/docker-stack/build.html#extending-the-image

**Comment by thesuperzapper** [comment]
If the intention of the constraints file is only intended to be used on the first `pip install` of airflow, we shouldn't implement `constraints.txt` support for `extraPipPackages`, so I will close this issue.
