### ISSUE TITLE
 sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by krestix** [airflow-helm/charts#227]
Hi, we using a k8s cluster on which we installed airflow2 via helm chart.
We're trying to run 300 tasks on airflow - and got this error: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: sorry, too many clients already
**i have tried the next configurations on helmchart value.yaml file:**
env:
  - name: "AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE"          ===> after this change airflow ui taking longer time to refresh pages
    value: "1000"
postgresql:
  enabled: true
  postgresqlExtendedConf:
    maxConnections: "1000"

**This is the postgres template values (airflow/charts/postgres/values.yaml):**
resources:
  requests:
    memory: 256Mi
    cpu: 250m

**Comment by thesuperzapper** [comment]
@krestix This issue is caused by airflow tasks all creating their own connections to the metadata database (Postgres), exceeding whatever `max_connections` is set on your Postgres instance.

__There are a few options to fix it:__
1. We could implement [PgBouncer](https://www.pgbouncer.org/features.html) in the chart, to pool the connections:
   * However, this would not work with MySQL, and I am not sure if there is an alternative (or if this issue can even occur in MySQL)
2. Increase the `max_connections` of your Postgres
3. Reduce the number of connections which airflow is making:
    * There are a few configs for airflow that do this, like `AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE`
    * However, after you have a large number of tasks, there is no avoiding lots of connections, due to how airflow is designed.

**Comment by thesuperzapper** [comment]
@krestix I do wonder if solving https://github.com/airflow-helm/charts/issues/233 (allowing Redis as a result_backend) will fix this issue for you?

**Comment by krestix** [comment]
@thesuperzapper 
Hi, we use KubernetesExecutor  - 
after using pgbouncer the issue with "no client connections" fixed
but we faced another problem
if we run many (8000 for exm.) jobs - most of them crash and loose the connection to the network.
