### ISSUE TITLE
ensure git-sync is the first init-container

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#276]
We created PR https://github.com/airflow-helm/charts/pull/255 to resolve the possibility of users storing plugins in their git-sync repo, causing the `check-db` to fail.

Init-containers are run [in the order they are declared](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior), so if the `git-sync` init-container is not declared first, the plugins will not exist when `check-db` runs, leading to a CrashLoopBackoff.

__We should order the init-containers so that `git-sync` is first init-container.__

**Comment by bradarndt** [comment]
I ran into a situation today where the fact that git-sync was not the first init-container actually caused it to fail (and thus my pods to not start successfully).  I believe that I was able to trace the root of the issue to the following sequence of events:

1. check-db pod runs - as part of running, it creates a logs directory at /opt/airflow/logs. 
2. git-sync pod runs and attempts to clone repo _however_ since the /dags (aka /opt/airflow) directory is not empty, the command fails

Addressing this issue (and setting the git-sync as the first container) fixes the issue.  I've submitted PR #307 to make the change.

As some additional commentary, I believe that the reason this wasn't an issue before (even though the check db container has always run before git sync) is that only with PR #255 was [the /opt/airflow volume actually mounted into the container](https://github.com/airflow-helm/charts/pull/255/files#diff-c47661b30b44f76310ceea6aa3e87628a760542cb8fdfae1f6d725c7ebbf0f6dR34) - thus allowing the logs directory to persist for other containers

**Comment by bradarndt** [comment]
Note that upon additional investigation/troubleshooting, I believe the particular complication that I was facing above was due to the fact that I was using /opt/airflow as the dags path (instead of a subpath thereof).  That being said, the referenced PR still is applicable to setting git sync as the first init-container
