### ISSUE TITLE
Move pip-install out of container start commands

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#3]
We should move pip-install out of the container start commands, as this forces us to work around the liveness/readiness probes timing out, because pip-install can take long amounts of time.

My idea is to put all the pip install inside an initContainer (into a non-persistent Volume), and prefix the `PYTHONPATH` of the main container as it starts to include the install folder.

**Comment by thesuperzapper** [comment]
If anyone wants to help out with this, feel free to raise a PR. Otherwise, I will get around to it eventually.

**Comment by aaron-trout** [comment]
I would go further and consider that installing packages at runtime is inherently flawed and can lead to instability and potentially security issues. Our airflow instance all of a sudden stopped working recently because some pip packages are no longer installable. Fixed by upgrading our airflow to the latest 1.x release, but we weren't that far behind (1.10.12 I think).

Saying that I guess it is reasonable for us to just build our own image and not use the install extra packages feature of the Helm chart, but perhaps that should be documented / reccomended for production deployments?

**Comment by thesuperzapper** [comment]
This has been done in version `8.0.0` of the chart, see PR: https://github.com/airflow-helm/charts/pull/96
