### ISSUE TITLE
Scheduler pod is not restarted after Airflow DB downtime

### ISSUE THREAD

**Issue by dktranzact** [airflow-helm/charts#361]
**What is your question?**
I'm using PostgreSQL as a backend DB. At some point DB becomes unavailable and after some downtime it become alive again, but scheduler pod lost connection to it and is not restarted. 
What can I check, any suggestion?

I am using version `2.1.2`

**Comment by thesuperzapper** [comment]
@dktranzact I have a feeling this is related to https://github.com/airflow-helm/charts/pull/351 (which will be fixed in the next chart release, `8.5.0`).

However, I am not clear why the scheduler wouldn't crash if the database becomes unavailable, can you share the logs of the scheduler pod when this happens?

**Comment by thesuperzapper** [comment]
@dktranzact can you confirm if [version `8.5.0`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#850---2021-08-19) of the chart resolves this issue for you?
