### ISSUE TITLE
rename `airflow.config` secret (remove empty strings from `stringData`)

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#362]
For users who installed the chart previous to PR https://github.com/airflow-helm/charts/pull/356, they will likely have empty strings for any `airflow.config` they have removed over time, this WILL cause problems for `AIRFLOW__XXXX` configs, as empty strings are often not valid values for airflow configs. (See issue: https://github.com/helm/helm/issues/10010)

__We should do these things:__
- Migrate remaining `stringData` keys in [config/secret-config.yaml](https://github.com/airflow-helm/charts/blob/0d83310780590ec78690aaea5b137ec63f511663/charts/airflow/templates/config/secret-config.yaml) to `data`
- Migrate all other Secrets using `stringData` to `data`
- Rename the secret to `{{ include "airflow.fullname" . }}-config-envs`, so any existing users will get a "fresh" Secret (with no empty-string keys)

**Comment by DJAyth** [comment]
Heads up that the change of renaming the secret is not a part of the Changelog where this change made it into a release: https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#fixed-8. That could stand to be there so that if the secret is referenced anywhere it gets updated. Like a podtemplate, which is how I found out this issue.
