### ISSUE TITLE
CONNECTION_CHECK_MAX_COUNT value for worker pods using KubernetesExecutor

### ISSUE THREAD

**Issue by emartgu** [airflow-helm/charts#416]
**What is your question?**

Hi, I have a question. The rendered pod_template.yaml now contains:
```
        ## enable the `/entrypoint` db connection check
        - name: CONNECTION_CHECK_MAX_COUNT
          value: "20"
       ...
        - name: CONNECTION_CHECK_MAX_COUNT
          value: "0"
```

Why did you set it first to 20:
https://github.com/airflow-helm/charts/pull/386/files#diff-2888d6df6c03d00cba8eac63b9c04078e2d4b5186e06debda5f3b011aaa28095R55

But then setting it to zero (which will be used as I understand it):
https://github.com/airflow-helm/charts/pull/386/files#diff-c47661b30b44f76310ceea6aa3e87628a760542cb8fdfae1f6d725c7ebbf0f6dR420

Should worker pods, when using KubernetesExecutor, have some CONNECTION_CHECK_MAX_COUNT value or zero?

We are using Helm chart 8.5.2 with Airflow 2.1.3.

**Comment by thesuperzapper** [comment]
@emartgu We don't use any `check-db` init-containers in the KubernetesExecutor worker Pods, so we let the `/entrypoint` take care of the DB check by setting `CONNECTION_CHECK_MAX_COUNT` to non-zero. But in the scheduler pod it would be redundant to use `CONNECTION_CHECK_MAX_COUNT` (due to the check-db init-container), so we set it to 0.

It is set twice is because of the way the templates of the chart are laid out (but realize that the FIRST definition in `env` takes precedence).
