### ISSUE TITLE
Remove env variable - DATABASE_PASSWORD

### ISSUE THREAD

**Issue by fanyinyi108** [airflow-helm/charts#421]
My feature request:

https://github.com/airflow-helm/charts/blob/3721cfd433b5a210361def6afd63b725f9ac4044/charts/airflow/templates/_helpers/pods.tpl#L413-L436

We can see these sentences may the causes lead to the exposure of our "DATABASE_PASSWORD" in our Rendered Template in each our dag - task instance.

So we are here to make a request to see if you could help remove / mask this environment variable.

![Screen Shot 2021-09-08 at 3 22 57 PM](https://user-images.githubusercontent.com/73573734/132572822-780ee759-0abf-4dd9-a602-71f56e35bb68.png)
![Screen Shot 2021-09-08 at 3 23 10 PM](https://user-images.githubusercontent.com/73573734/132572824-3d25d83d-c895-4262-84c9-b02dacb06b00.png)

**Comment by thesuperzapper** [comment]
@fanyinyi108 its not possible to remove this variable, as it's how the chart is able to URL-encode the password for users:
- [`DATABASE_PASSWORD_CMD`](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/config/secret-config-envs.yaml#L45-L46)
- [`DATABASE_SQLALCHEMY_CMD `](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/config/secret-config-envs.yaml#L48-L55)
- [`AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD `](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/config/secret-config-envs.yaml#L99)

---

I think this is a direct result of using [BashOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html), (because the `env` Python argument is templated by Jinja).
 
Can you clarify what you are setting `env` as in your `BashOperator`, because it seems to not print anything in my testing when left empty?

**Comment by vix633** [comment]
Hey @thesuperzapper,

FYI, this seems to be leaking in another place as well. Looks like the init commandline echos the plain text pass to python, so this becomes detectable in logs. Example below:

`bash -c eval "echo -n "postgresql+psycopg2://$(eval echo "airflow_user" | python3 -c "import urllib.parse; encoded_user = urllib.parse.quote(input()); print(encoded_user)"):$(eval echo "snippedOutPasswordWasHere" | python3 -c "import urllib.parse; encoded_pass = urllib.parse.quote(input()); print(encoded_pass)")@airflow.snip.rds.amazonaws.com:5432/airflow""`

I'm wondering if there could be a better way to inject it at init.

**Comment by thesuperzapper** [comment]
@vix633 can you clarify which logs you are seeing a plaintext password in?

**Comment by vix633** [comment]
> @vix633 can you clarify which logs you are seeing a plaintext password in?

I'm using a runtime container security tool that has detections from stdin(Falco), and this was one of the detections. That being said, there's a danger here that if the command fails for any reason it will also direct that cmdline to stderr which will get picked up by most workload monitoring

**Comment by thesuperzapper** [comment]
@vix633 because [we are using](https://github.com/airflow-helm/charts/blob/airflow-8.9.0/charts/airflow/templates/config/secret-config-envs.yaml#L147) the [`AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD`](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html) variable there should not be any way for it to print out on error. If there is, that would be a problem with upstream airflow itself.

For reference, I just checked and it's not ending up in the `~/.bash_history` file, so that's a good sign that however Airflow is running these commands, it does it with history disabled.

---

If you want to do some security testing on cases where the `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD` fails, to see if it logs anything anywhere, I am sure the Airflow community would appreciate your efforts.

__WARNING:__ if you do find a security issue after the above testing, please [responsibly disclose it to Airflow](https://github.com/apache/airflow/security) and if applicable [this repo](https://github.com/airflow-helm/charts/security) also, so we can coordinate a fix.

**Comment by vix633** [comment]
> @vix633 because [we are using](https://github.com/airflow-helm/charts/blob/airflow-8.9.0/charts/airflow/templates/config/secret-config-envs.yaml#L147) the [`AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD`](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html) variable there should not be any way for it to print out on error. If there is, that would be a problem with upstream airflow itself.
> 
> For reference, I just checked and it's not ending up in the `~/.bash_history` file, so that's a good sign that however Airflow is running these commands, it does it with history disabled.
> 
> If you want to do some security testing on cases where the `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD` fails, to see if it logs anything anywhere, I am sure the Airflow community would appreciate your efforts.
> 
> **WARNING:** if you do find a security issue after the above testing, please [responsibly disclose it to Airflow](https://github.com/apache/airflow/security) and if applicable [this repo](https://github.com/airflow-helm/charts/security) also, so we can coordinate a fix.

Thanks @thesuperzapper!

The failure mode I'm thinking of is at `dumb-init` stage; I'll try to validate my hypothesis with some testing.

In the meantime, though. You don't see a better avenue to inject this pass at init?

**Comment by thesuperzapper** [comment]
@vix633 Maybe I am misunderstanding, what `dumb-init` are you talking about, that's only used to kick off the airflow process in the container, that environment variable should not be read until airflow itself starts.

Did I miss something?

Either way, it will be interesting to see your testing results.

**Comment by vix633** [comment]
@thesuperzapper

Thats exacly the `dumb-init` that I'm talking about, that's the one that dumps the plain text pass into stdin there.

My hypothesis was hopefully getting the pod to throw during startup and bubble up the full init command line. The actual command line that is used to establish the host connection to the database (the cmdline I posted initially in this issue).

 What I tried to do is to give an invalid path in the connection string, which failed just fine in Python -- but exited gracefully and didn't bubble up all the way to the OS, throwing the command line args as I'd hoped it might.
