### ISSUE TITLE
GitSync-sidecar for (new) db-migration pod required?

### ISSUE THREAD

**Issue by jherrmannNetfonds** [airflow-helm/charts#423]
**What is your question?**

Hi, I am using google kubernetes autopilot cluster for our airflow deployment. On K8 Autopilot cluster you pay by requested resources. If I specify the resources for the db-migration pod the sidecar requests additional `CPU: 500m` and `Memory: 2GB` by default if it is not limited by the resource option for the gitSync sidecar. 
I was wondering if the sidecar is even needed for the db-migration pod?

**Comment by thesuperzapper** [comment]
@jherrmannNetfonds thanks for your question!

You can [see in the YAML](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/db-migrations/db-migrations-deployment.yaml#L108-L109), that the `git-sync` container is included for `db-migrations` so that "airflow plugins" and other "python packages" can be stored in your dags repo. When your not doing that, I agree that syncing the repo is a bit of waste (but the actual CPU/RAM usage is very low).

---

For your specific case, I see that GKE Autopilot has [Minimum Resources which a Pod can request](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#allowable_resource_ranges), along with [Default Requests for each Container in a Pod](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#default_container_resource_requests), so if you're not specifying the resource request of the git-sync container with [`dags.gitSync.resources`](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/values.yaml#L1088-L1092), you will end up with an extra `CPU: 500m` and `Memory: 2GB`. 

__You have a couple of options:__
1. Just disable the `db-migrations` Deployment, by enabling [`airflow.dbMigrations.runAsJob`](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/values.yaml#L340-L345) 
    - (WARNING: this will not work if you are using the `--wait` flag on `helm install`)
2. Ensure you are setting [`dags.gitSync.resources`](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/values.yaml#L1088-L1092) to a very small value

**Comment by jherrmannNetfonds** [comment]
Thanks for the quick reply
1. I do not want to switch back to runAsJob because of the `--wait` flag and the problems which arise with CI/CD
2. I set `dags.gitSync.resources` so GKE Autopilot will not take the full 500mb. So "Problem Solved"
I was just wondering for what reason the `db-migrations` script needs access to dags and "python packages". From what I can tell from the [code](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/db-migrations/_helpers/code.tpl), it would work perfectly fine without the sidecar. If the sidecar is removed  from [this YAML](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/db-migrations/db-migrations-deployment.yaml#L108-L109) all other Pods still have the sidecar and git sync should work. Am I'm missing something?

**Comment by thesuperzapper** [comment]
@jherrmannNetfonds 

The issue is that "airflow plugins" are imported when you import `airflow` in Python, which will fail if `AIRFLOW__CORE__XCOM_BACKEND` is set to a package that lives in your git-repo (see https://github.com/airflow-helm/charts/issues/245).

We could create a value like `dags.gitSync.dagsOnly`, which lets users tell us that it's safe to only run git-sync in the main airflow components (and not all the other python-code deployments we run). But this might verge on too complex for most users to ever understand.

Also, what specific issue are you having with `runAsJob` in CI/CD (other than the `--wait` issue)?

**Comment by jherrmannNetfonds** [comment]
Ok, I understand, thx for the explanation.
Regarding the runAsJob option, we only had an issue with wait when using helmfile. Currently we migrate to flux. Will see if any issues show up.
