### ISSUE TITLE
DB-Migrations not able to rollback after partial successfful rollout. 

### ISSUE THREAD

**Issue by jensgrnb** [airflow-helm/charts#461]
Hello Hello 

I'm running into a rollback problem on my GKE cluster. 

I'm using the helm chart version 8.5.0 with airflow@2.1.2

Steps taken by me leading to a broken state: 
1. 
upgrade airflow tag to  airflow@2.2.1
2. 
Rollout: All resources are rolled out succesfully except the worker pod which ends in a crashloop because of some conflict with celery. 
3. 
Try rollback to previous healthy state
4. 
db-migrations container ends up in a crashloop because:
```
alembic.script.revision.ResolutionError: No such revision or branch 'ccde3e26fe78'
```

This is a known problem with the metadatabase. I thought this was resolved in this relatively new helm chart version I'm using. 

short google suggest to drop the alembic_version table in the metadatabase, but I'm wary of doing this as last time this happened I had to recreate the metadatabase.

**Comment by jensgrnb** [comment]
I fixed the issue this time, by simply steaming ahead with the upgrade to airflow@2.2.1, but in essence I can't really trust the rollback mechanism any longer. 

Is there any way I can remedy this? Where is this revision/branch number stored by alembic, so I can fix the disconnect?

**Comment by thesuperzapper** [comment]
@jensgrnb If you update airflow versions, the chart will run `airflow db upgrade` (in the db-migrations deployment or job) which will apply any schema changes for that new airflow version. Because airflow itself doesn't support downgrading the database schema, you are then stuck with the newer version unless you replace your database, or manually rollback the schema changes (not recommended).

**Comment by jensgrnb** [comment]
Thank you for response! I see, and there's no way that the chart can mitigate this issue by like putting the db upgrade at the end of the dependency chain between resources? 

My problem is that I'm trying to handover the maintenance of the chart to a engineering group, and what they will probably be mostly doing is keep up with with airflow version counter.

But as I understand your msg, this kind of modification basically gives them no failsafe rollback mechanism.

**Comment by jensgrnb** [comment]
I see that this is a reported limitation on Airflow's behalf, and google have some suggestions on how to remedy it, but basically it's not the helm charts problem. Thanks.

**Comment by thesuperzapper** [comment]
@jensgrnb if you are not using a tool like argo-cd (which uses `helm template ...` rather than `helm install ...`), then you can set `airflow.dbMigrations.runAsJob` to `true` so that the db-migrations are run as a [post-install Job](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/db-migrations/db-migrations-job.yaml), rather than [a Deployment](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/db-migrations/db-migrations-deployment.yaml).

**Comment by jensgrnb** [comment]
Okay, yeah unfortunately I'm bound to argocd :(
