### ISSUE TITLE
airflow db-migration-init container not optional

### ISSUE THREAD

**Issue by pindge** [airflow-helm/charts#473]
## What is the bug?

https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-deployment.yaml#L93 this is always required, even when `dbmigration enabled` is set to false

## What version of the chart are you using?

I am using version `8.5.2` of this chart.

## What version of Kubernetes are you using?

```console
######## PASTE `kubectl version` BELOW ########
Client Version: ...
Server Version: ...
######## PASTE `kubectl version` ABOVE ########
```

## What version of Helm are you using?

```console
######## PASTE `helm version` BELOW ########
version.BuildInfo{....
######## PASTE `helm version` ABOVE ########
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
######## PASTE values.yaml BELOW ########
airflow:
  ...
######## PASTE values.yaml ABOVE ########
```

</details>

**Comment by thesuperzapper** [comment]
@pindge its still important for the webserver to not start until the correct DB Migrations have been applied (otherwise it might not work, or may corrupt your database).

The `airflow.dbMigrations.enabled` feature is for people who want to manually run `airflow db upgrade` when needed, rather than depending on the chart to do it for them in a Job/Deployment.
