### ISSUE TITLE
How do I retain ownership of the mounted git repo? And is it possible to only sync a specific folder from git?

### ISSUE THREAD

**Issue by Mouftizo** [airflow-helm/charts#53]
Hello maintainers. Thanks for putting together this project, I found documentation for almost every single step I was stuck at. 

I am currently using the `git-sync` mount to pull my DAGs from a repository. I am using Data Build Tool ([dbt](https://www.getdbt.com/)) alongside with airflow, and wanted to use the sync'd git repo to mount both the dags and dbt models (files that need to be read/written-to by dbt) to keep everything in one repo. I found that after mounting, the dags folder ownership changes from the airflow user to become the root user. I have further documented this [here](https://stackoverflow.com/questions/65457870/how-can-i-avoid-permission-denied-errors-when-mounting-a-container-into-my-dep?noredirect=1#comment115746232_65457870) and attempted to resolve it through StackOverflow before heading here. 

My question(s) to you:
-  Can I (and should I?) mount other assets (not just Dags) via the git-sync container? If so, how can I retain the ownership of the mounted folders?
- <s>Let's say I only want to mount the dags. Is it possible to only mount a particular folder from the git repo? I am asking because maybe I want to separate dbt code from airflow code, yet keep in the same repo (so only sync the dags folder in the repo)</s>

I am happy to provide any further details needed = ) 

**Update:**
Regarding the second question, I found a hack around that by using `.airflowignore` which has been discussed [here](https://stackoverflow.com/questions/53660558/airflow-dag-folder-how-to-ignore-notebook-checkpoints)

**Comment by thesuperzapper** [comment]
@Mouftizo  Someone asked a similar question before, but it seemed they deleted the issue.

The gist of it is, we assume that everything under your `dags.path` folder is **exactly the same as what is in your git repo**, as you can [see here](https://github.com/airflow-helm/charts/blob/airflow-7.16.0/charts/airflow/templates/config/configmap-scripts-git.yaml#L70-L77) we remove any files added to the `dags.path` folder every sync (this is partially why the linux folder permissions don't allow changes inside airflow tasks).

For your case, I am not sure about the best way to use git-sync with dbt. However, you should consider storing your DBT code inside the git repo, and both compiling/running the dbt stuff it in the same airflow task, (because there is no guarantee that two consecutive tasks will run on the same airflow-worker, and otherwise the generated dbt files will not necessarily be available).

**Comment by Mouftizo** [comment]
@thesuperzapper Sounds good! Thanks for sharing the relevant code part = ). I ended up using the PodOperator and Dockerizing dbt altogether and having at a separate repo. Let's see how that turns out.
