### ISSUE TITLE
Helm Chart: Community vs Offical 

### ISSUE THREAD

**Issue by acelinkio** [airflow-helm/charts#846]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Description

Is this helm chart still needed?  The last release for this project was 8 months ago.  Should this project be archived as Airflow has their official helm chart offering now.  https://github.com/apache/airflow/releases/tag/helm-chart%2F1.13.1

Their last release was 2 weeks ago https://artifacthub.io/packages/helm/apache-airflow/airflow

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [ ] I can provide feedback!

**Comment by thesuperzapper** [comment]
@acelinkio I believe the community chart is still needed as it's still very widely used.

While I agree that it would be great to release more often, except when something breaks upstream (like I am resolving for Airflow 2.9 right now), you can continue to use the chart with any version of airflow you like.

Fundamentally, the two charts take different approaches to many things (mainly around the structure of values, and the fact that the community chart aims to support all versions of airflow, rather than just the latest).
